{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOG8V5dPhjFfmx60ZTQEvL2"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 9,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "-F9Xz8B2P5Bm",
        "outputId": "85db1d8d-4b52-468a-8f4f-df7ce1247efe"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Laberinto generado:\n",
            "[0, 0, 0, 0, 1, 1]\n",
            "[1, 1, 1, 0, 0, 1]\n",
            "[1, 1, 1, 1, 0, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 6]\n",
            "[1, 1, 1, 1, 1, 2]\n",
            "Llegaste a una celda trivia en (4, 5)\n",
            "Pregunta trivia: ¿Cuánto es 7x7? 49\n",
            "¡Correcto!\n",
            "[5, 0, 0, 0, 1, 1]\n",
            "[1, 1, 1, 0, 0, 1]\n",
            "[1, 1, 1, 1, 0, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 2]\n",
            "[5, 5, 0, 0, 1, 1]\n",
            "[1, 1, 1, 0, 0, 1]\n",
            "[1, 1, 1, 1, 0, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 2]\n",
            "[5, 5, 5, 0, 1, 1]\n",
            "[1, 1, 1, 0, 0, 1]\n",
            "[1, 1, 1, 1, 0, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 2]\n",
            "[5, 5, 5, 5, 1, 1]\n",
            "[1, 1, 1, 0, 0, 1]\n",
            "[1, 1, 1, 1, 0, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 2]\n",
            "[5, 5, 5, 5, 1, 1]\n",
            "[1, 1, 1, 5, 0, 1]\n",
            "[1, 1, 1, 1, 0, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 2]\n",
            "[5, 5, 5, 5, 1, 1]\n",
            "[1, 1, 1, 5, 5, 1]\n",
            "[1, 1, 1, 1, 0, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 2]\n",
            "[5, 5, 5, 5, 1, 1]\n",
            "[1, 1, 1, 5, 5, 1]\n",
            "[1, 1, 1, 1, 5, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 2]\n",
            "[5, 5, 5, 5, 1, 1]\n",
            "[1, 1, 1, 5, 5, 1]\n",
            "[1, 1, 1, 1, 5, 5]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 2]\n",
            "[5, 5, 5, 5, 1, 1]\n",
            "[1, 1, 1, 5, 5, 1]\n",
            "[1, 1, 1, 1, 5, 5]\n",
            "[1, 1, 1, 1, 1, 5]\n",
            "[1, 1, 1, 1, 1, 0]\n",
            "[1, 1, 1, 1, 1, 2]\n",
            "[5, 5, 5, 5, 1, 1]\n",
            "[1, 1, 1, 5, 5, 1]\n",
            "[1, 1, 1, 1, 5, 5]\n",
            "[1, 1, 1, 1, 1, 5]\n",
            "[1, 1, 1, 1, 1, 5]\n",
            "[1, 1, 1, 1, 1, 2]\n",
            "[5, 5, 5, 5, 1, 1]\n",
            "[1, 1, 1, 5, 5, 1]\n",
            "[1, 1, 1, 1, 5, 5]\n",
            "[1, 1, 1, 1, 1, 5]\n",
            "[1, 1, 1, 1, 1, 5]\n",
            "[1, 1, 1, 1, 1, 5]\n"
          ]
        }
      ],
      "source": [
        "import random\n",
        "import time\n",
        "import os\n",
        "\n",
        "def generar_laberinto(n):\n",
        "    laberinto = []\n",
        "    for i in range(n):\n",
        "        fila = []\n",
        "        for j in range(n):\n",
        "            fila.append(1)\n",
        "        laberinto.append(fila)\n",
        "\n",
        "    laberinto[0][0] = 0\n",
        "    laberinto[n-1][n-1] = 2\n",
        "    i, j = 0, 0\n",
        "    camino = [(0, 0)]\n",
        "\n",
        "    while (i, j) != (n-1, n-1):\n",
        "        laberinto[i][j] = 0\n",
        "        if i < n-1 and j < n-1:\n",
        "            if random.random() < 0.5:\n",
        "                i += 1\n",
        "            else:\n",
        "                j += 1\n",
        "        elif i < n-1:\n",
        "            i += 1\n",
        "        elif j < n-1:\n",
        "            j += 1\n",
        "        camino.append((i, j))\n",
        "\n",
        "    trivia_pos = random.choice(camino[:-1])\n",
        "    laberinto[trivia_pos[0]][trivia_pos[1]] = 6\n",
        "\n",
        "    return laberinto\n",
        "\n",
        "def trivia():\n",
        "    pregunta = \"¿Cuánto es 7x7?\"\n",
        "    respuesta_correcta = 49\n",
        "\n",
        "    while True:\n",
        "        try:\n",
        "            respuesta = int(input(f\"Pregunta trivia: {pregunta} \"))\n",
        "            if respuesta == respuesta_correcta:\n",
        "                print(\"¡Correcto!\")\n",
        "                return True\n",
        "            else:\n",
        "                print(\"Incorrecto. Intenta de nuevo.\")\n",
        "        except ValueError:\n",
        "            print(\"Por favor, ingresa un número válido.\")\n",
        "\n",
        "def resolver_laberinto(laberinto):\n",
        "    n = len(laberinto)\n",
        "    m = len(laberinto[0])\n",
        "    dp = [[0 for j in range(m)] for i in range(n)]\n",
        "    dp[0][0] = 1\n",
        "    for j in range(1, m):\n",
        "        if laberinto[0][j] == 0:\n",
        "            dp[0][j] = dp[0][j-1]\n",
        "    for i in range(1, n):\n",
        "        if laberinto[i][0] == 0:\n",
        "            dp[i][0] = dp[i-1][0]\n",
        "    for i in range(1, n):\n",
        "        for j in range(1, m):\n",
        "            if laberinto[i][j] in [0, 2, 6]:\n",
        "                if laberinto[i][j] == 6:\n",
        "                    print(f\"Llegaste a una celda trivia en ({i}, {j})\")\n",
        "                    if trivia():\n",
        "                        laberinto[i][j] = 0\n",
        "                if laberinto[i][j] == 0 or laberinto[i][j] == 2:\n",
        "                    dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n",
        "\n",
        "    return dp\n",
        "\n",
        "def imprimir_camino(camino, laberinto):\n",
        "    n = len(laberinto)\n",
        "    m = len(laberinto[0])\n",
        "    for i in range(n):\n",
        "        for j in range(m):\n",
        "            if camino[i][j] > 0:\n",
        "                laberinto[i][j] = 9\n",
        "                os.system(\"cls\")\n",
        "                for fila in laberinto:\n",
        "                    print(fila)\n",
        "                time.sleep(0.5)\n",
        "    return laberinto\n",
        "\n",
        "\n",
        "laberinto = generar_laberinto(10)\n",
        "print(\"Laberinto generado:\")\n",
        "for fila in laberinto:\n",
        "    print(fila)\n",
        "\n",
        "camino_dp = resolver_laberinto(laberinto)\n",
        "imprimir_camino(camino_dp, laberinto)\n",
        "print(\"Laberinto resuelto\")\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "NcEkj9Mxia7j"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}